#指南——https://docs.docker.com/compose/compose-file/
version: "3"
services:
  ### 数据库
  kitchen-db:
    image: kitchen.com/kitchen-db:latest
    build: ./@docker-middleware/mysql
    #volumes:
    #  - /data/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
  ### 服务注册中心
  service-registry-center:
    image: zookeeper:3.4.12
    ports:
      - "2181:2181"
    restart: always
  ### 网关服务
  api-portal:
    image: kitchen.com/api-portal:latest
    build: ./api-portal/target
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=prod
      - dubbo.registry.address=service-registry-center:2181
    restart: always
  ### 微服务
  microservice-one:
    image: kitchen.com/microservice-one:latest
    build: ./micro-services/demo-microservice1/demo-service-one/target
    environment:
      - spring.profiles.active=prod
      - spring.datasource.url=jdbc:mysql://kitchen-db:3306/kitchen_db?useUnicode=true&characterEncoding=utf-8
      - spring.datasource.username=root
      - spring.datasource.password=123456
      - dubbo.registry.address=service-registry-center:2181
      - dubbo.protocol.port=-1
    restart: always

logging:
  ### 默认的日志输出驱动，设置为none则关闭日志输出（driver: "none"）
  driver: "json-file"
  options:
    ### 限制docker日志文件（/var/lib/docker/containers/***-json.log）的大小和保留文件的最大个数
    max-size: "10m"
    max-file: "3"